name: ProdRelease
on: 
  workflow_dispatch:
    inputs:
      releaseCard:
        description: 'Release card'     
        required: true
        
jobs:
  printInputs:
    name: Dispatch to `other-repo`
    runs-on: ubuntu-latest
    steps:
      - name: ExecuteTrigger
          uses: fjogeleit/http-request-action@master
          with:
            url: 'https://9dca4b367114.ngrok.io/api/projects/SDLC-GitFlow/apps/static-branch-demo/webhooks/github/cicd/notify'
            method: 'POST'
            data: '{"issueId": "${{ github.event.inputs.releaseCard }}"}'
