name: manualworkflow
on: 
  workflow_dispatch:
    inputs:
      releaseCard:
        description: 'Release card'     
        required: true
        default: 'warning'
      envToDeploy:
        description: 'Environment' 
        required: true
        default: 'warning'
        
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.releaseCard }}"
        echo "Tags: ${{ github.event.inputs.envToDeploy }}" 
